name: Post-Merge Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]
  workflow_dispatch:
    inputs:
      branch_to_validate:
        description: 'Branch that was merged (for validation)'
        required: false
        default: 'copilot/fix-71a13388-9183-473b-a4d1-dadd0595d643'
      pr_number:
        description: 'PR number to validate'
        required: false
        default: '2'

jobs:
  post-merge-validation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for merge validation
    
    - name: Set up validation environment
      run: |
        # Make validation script executable
        chmod +x scripts/post-merge-validation.sh
        
        # Set environment variables for validation
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "MERGED_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "MERGED_BRANCH=${{ github.event.inputs.branch_to_validate }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
        else
          echo "MERGED_BRANCH=copilot/fix-71a13388-9183-473b-a4d1-dadd0595d643" >> $GITHUB_ENV
          echo "PR_NUMBER=2" >> $GITHUB_ENV
        fi
    
    - name: Run post-merge validation
      run: |
        echo "Running post-merge validation..."
        echo "Validating merge of branch: $MERGED_BRANCH"
        echo "PR number: $PR_NUMBER"
        
        # Update script with current validation parameters
        sed -i "s/MERGED_BRANCH=\".*\"/MERGED_BRANCH=\"$MERGED_BRANCH\"/" scripts/post-merge-validation.sh
        sed -i "s/PR_NUMBER=\".*\"/PR_NUMBER=\"$PR_NUMBER\"/" scripts/post-merge-validation.sh
        
        # Run validation script
        ./scripts/post-merge-validation.sh
      continue-on-error: true
      id: validation
    
    - name: Generate validation report
      run: |
        echo "## Post-Merge Validation Report" > validation-report.md
        echo "" >> validation-report.md
        echo "**Branch Validated**: $MERGED_BRANCH" >> validation-report.md
        echo "**PR Number**: $PR_NUMBER" >> validation-report.md
        echo "**Validation Date**: $(date)" >> validation-report.md
        echo "**Validation Status**: ${{ steps.validation.outcome }}" >> validation-report.md
        echo "" >> validation-report.md
        
        if [ "${{ steps.validation.outcome }}" == "success" ]; then
          echo "✅ **Result**: All validation checks passed" >> validation-report.md
        else
          echo "⚠️ **Result**: Some validation checks failed or had warnings" >> validation-report.md
        fi
        
        echo "" >> validation-report.md
        echo "### Validation Details" >> validation-report.md
        echo "- Merge integration: Checked" >> validation-report.md
        echo "- Branch cleanup: Verified" >> validation-report.md
        echo "- Repository structure: Validated" >> validation-report.md
        echo "- Residual issues: Scanned" >> validation-report.md
        echo "" >> validation-report.md
        echo "### Recommendations" >> validation-report.md
        echo "- Review validation script output for specific details" >> validation-report.md
        echo "- Address any warnings or failures identified" >> validation-report.md
        echo "- Consider running manual validation if needed" >> validation-report.md
        
        # Display report
        cat validation-report.md
    
    - name: Upload validation report
      uses: actions/upload-artifact@v4
      with:
        name: post-merge-validation-report
        path: validation-report.md
        retention-days: 30
    
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('validation-report.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: report
          });
    
    - name: Set job status
      run: |
        if [ "${{ steps.validation.outcome }}" == "success" ]; then
          echo "✅ Post-merge validation completed successfully"
          exit 0
        else
          echo "⚠️ Post-merge validation completed with warnings"
          exit 0  # Don't fail the workflow, just report warnings
        fi